# [START django_app]
runtime: python39

env_variables:
#  add the environment variables HERE
  PROJECT : "#TODO my-project-HERE"
  LOCATION : "#TODO my-location-HERE"
  QUEUE_NAME : "#TODO my-queue-name-HERE"
  BUCKET_NAME: "#TODO my-bucket-name-HERE"

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]